version: "3"

services:
  app:
    container_name: twitterApi
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/twwiterapi
      - app-gems:/app-gems
    env_file:
      - ".env"

volumes:
  app-gems:
